package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Adjunto generated by hbm2java
 */
@Entity
@Table(name = "adjunto", catalog = "cer_db")
public class Adjunto implements java.io.Serializable {

	private AdjuntoId id;
	private Documento documento;

	public Adjunto() {
	}

	public Adjunto(AdjuntoId id) {
		this.id = id;
	}

	public Adjunto(AdjuntoId id, Documento documento) {
		this.id = id;
		this.documento = documento;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDocumento", column = @Column(name = "id_documento", nullable = false)),
			@AttributeOverride(name = "idDocumentoAdjunto", column = @Column(name = "id_documento_adjunto", nullable = false)) })
	public AdjuntoId getId() {
		return this.id;
	}

	public void setId(AdjuntoId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

}
