package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cc generated by hbm2java
 */
@Entity
@Table(name = "cc", catalog = "cer_db")
public class Cc implements java.io.Serializable {

	private Integer idCc;
	private Resolucion resolucion;
	private String despacho;

	public Cc() {
	}

	public Cc(String despacho) {
		this.despacho = despacho;
	}

	public Cc(Resolucion resolucion, String despacho) {
		this.resolucion = resolucion;
		this.despacho = despacho;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cc", unique = true, nullable = false)
	public Integer getIdCc() {
		return this.idCc;
	}

	public void setIdCc(Integer idCc) {
		this.idCc = idCc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion")
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "despacho", nullable = false, length = 50)
	public String getDespacho() {
		return this.despacho;
	}

	public void setDespacho(String despacho) {
		this.despacho = despacho;
	}

}
