package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Consideracionresolucion generated by hbm2java
 */
@Entity
@Table(name = "consideracionresolucion", catalog = "cer_db")
public class Consideracionresolucion implements java.io.Serializable {

	private ConsideracionresolucionId id;
	private Resolucion resolucion;
	private Consideracion consideracion;

	public Consideracionresolucion() {
	}

	public Consideracionresolucion(ConsideracionresolucionId id, Resolucion resolucion) {
		this.id = id;
		this.resolucion = resolucion;
	}

	public Consideracionresolucion(ConsideracionresolucionId id, Resolucion resolucion, Consideracion consideracion) {
		this.id = id;
		this.resolucion = resolucion;
		this.consideracion = consideracion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idResolucion", column = @Column(name = "id_resolucion", nullable = false)),
			@AttributeOverride(name = "idConsideracion", column = @Column(name = "id_consideracion", nullable = false)) })
	public ConsideracionresolucionId getId() {
		return this.id;
	}

	public void setId(ConsideracionresolucionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion", nullable = false, insertable = false, updatable = false)
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "consideracionresolucion")
	public Consideracion getConsideracion() {
		return this.consideracion;
	}

	public void setConsideracion(Consideracion consideracion) {
		this.consideracion = consideracion;
	}

}
