package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Consideracion generated by hbm2java
 */
@Entity
@Table(name = "consideracion", catalog = "cer_db")
public class Consideracion implements java.io.Serializable {

	private Integer idConsideracion;
	private Consideracionresolucion consideracionresolucion;
	private String consideracionText;

	public Consideracion() {
	}

	public Consideracion(Consideracionresolucion consideracionresolucion, String consideracionText) {
		this.consideracionresolucion = consideracionresolucion;
		this.consideracionText = consideracionText;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "consideracionresolucion"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_consideracion", unique = true, nullable = false)
	public Integer getIdConsideracion() {
		return this.idConsideracion;
	}

	public void setIdConsideracion(Integer idConsideracion) {
		this.idConsideracion = idConsideracion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Consideracionresolucion getConsideracionresolucion() {
		return this.consideracionresolucion;
	}

	public void setConsideracionresolucion(Consideracionresolucion consideracionresolucion) {
		this.consideracionresolucion = consideracionresolucion;
	}

	@Column(name = "consideracion_text", nullable = false, length = 65535)
	public String getConsideracionText() {
		return this.consideracionText;
	}

	public void setConsideracionText(String consideracionText) {
		this.consideracionText = consideracionText;
	}

}
