package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Datoadicional generated by hbm2java
 */
@Entity
@Table(name = "datoadicional", catalog = "cer_db")
public class Datoadicional implements java.io.Serializable {

	private Integer idDatoAdicional;
	private Documentoadjuntodatoadicional documentoadjuntodatoadicional;
	private String tipoDato;
	private String datoAdicional;
	private String descripcionOpcional;

	public Datoadicional() {
	}

	public Datoadicional(Documentoadjuntodatoadicional documentoadjuntodatoadicional, String tipoDato,
			String datoAdicional) {
		this.documentoadjuntodatoadicional = documentoadjuntodatoadicional;
		this.tipoDato = tipoDato;
		this.datoAdicional = datoAdicional;
	}

	public Datoadicional(Documentoadjuntodatoadicional documentoadjuntodatoadicional, String tipoDato,
			String datoAdicional, String descripcionOpcional) {
		this.documentoadjuntodatoadicional = documentoadjuntodatoadicional;
		this.tipoDato = tipoDato;
		this.datoAdicional = datoAdicional;
		this.descripcionOpcional = descripcionOpcional;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "documentoadjuntodatoadicional"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_dato_adicional", unique = true, nullable = false)
	public Integer getIdDatoAdicional() {
		return this.idDatoAdicional;
	}

	public void setIdDatoAdicional(Integer idDatoAdicional) {
		this.idDatoAdicional = idDatoAdicional;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Documentoadjuntodatoadicional getDocumentoadjuntodatoadicional() {
		return this.documentoadjuntodatoadicional;
	}

	public void setDocumentoadjuntodatoadicional(Documentoadjuntodatoadicional documentoadjuntodatoadicional) {
		this.documentoadjuntodatoadicional = documentoadjuntodatoadicional;
	}

	@Column(name = "tipo_dato", nullable = false, length = 30)
	public String getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(String tipoDato) {
		this.tipoDato = tipoDato;
	}

	@Column(name = "dato_adicional", nullable = false, length = 30)
	public String getDatoAdicional() {
		return this.datoAdicional;
	}

	public void setDatoAdicional(String datoAdicional) {
		this.datoAdicional = datoAdicional;
	}

	@Column(name = "descripcion_opcional", length = 65535)
	public String getDescripcionOpcional() {
		return this.descripcionOpcional;
	}

	public void setDescripcionOpcional(String descripcionOpcional) {
		this.descripcionOpcional = descripcionOpcional;
	}

}
