package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DecretosresolucionId generated by hbm2java
 */
@Embeddable
public class DecretosresolucionId implements java.io.Serializable {

	private int idResolucion;
	private int idDecreto;

	public DecretosresolucionId() {
	}

	public DecretosresolucionId(int idResolucion, int idDecreto) {
		this.idResolucion = idResolucion;
		this.idDecreto = idDecreto;
	}

	@Column(name = "id_resolucion", nullable = false)
	public int getIdResolucion() {
		return this.idResolucion;
	}

	public void setIdResolucion(int idResolucion) {
		this.idResolucion = idResolucion;
	}

	@Column(name = "id_decreto", nullable = false)
	public int getIdDecreto() {
		return this.idDecreto;
	}

	public void setIdDecreto(int idDecreto) {
		this.idDecreto = idDecreto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DecretosresolucionId))
			return false;
		DecretosresolucionId castOther = (DecretosresolucionId) other;

		return (this.getIdResolucion() == castOther.getIdResolucion())
				&& (this.getIdDecreto() == castOther.getIdDecreto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdResolucion();
		result = 37 * result + this.getIdDecreto();
		return result;
	}

}
