package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dictamen generated by hbm2java
 */
@Entity
@Table(name = "dictamen", catalog = "cer_db")
public class Dictamen implements java.io.Serializable {

	private Integer idDecretoResolucion;
	private Resolucion resolucion;
	private int nroArticulo;
	private String contenido;

	public Dictamen() {
	}

	public Dictamen(Resolucion resolucion, int nroArticulo, String contenido) {
		this.resolucion = resolucion;
		this.nroArticulo = nroArticulo;
		this.contenido = contenido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_decreto_resolucion", unique = true, nullable = false)
	public Integer getIdDecretoResolucion() {
		return this.idDecretoResolucion;
	}

	public void setIdDecretoResolucion(Integer idDecretoResolucion) {
		this.idDecretoResolucion = idDecretoResolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion", nullable = false)
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "nro_articulo", nullable = false)
	public int getNroArticulo() {
		return this.nroArticulo;
	}

	public void setNroArticulo(int nroArticulo) {
		this.nroArticulo = nroArticulo;
	}

	@Column(name = "contenido", nullable = false)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

}
