package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentoOrigen generated by hbm2java
 */
@Entity
@Table(name = "documento_origen", catalog = "cer_db")
public class DocumentoOrigen implements java.io.Serializable {

	private Integer idDocumentoOrigen;
	private Persona persona;
	private String codigoDocumentoOrigen;
	private String descripcion;
	private Date fechaPresentacion;
	private String estadoDocumentoOrigen;
	private Set<Resolucion> resolucions = new HashSet<Resolucion>(0);
	private Set<Resolucion> resolucions_1 = new HashSet<Resolucion>(0);

	public DocumentoOrigen() {
	}

	public DocumentoOrigen(String codigoDocumentoOrigen, String descripcion, String estadoDocumentoOrigen) {
		this.codigoDocumentoOrigen = codigoDocumentoOrigen;
		this.descripcion = descripcion;
		this.estadoDocumentoOrigen = estadoDocumentoOrigen;
	}

	public DocumentoOrigen(Persona persona, String codigoDocumentoOrigen, String descripcion, Date fechaPresentacion,
			String estadoDocumentoOrigen, Set<Resolucion> resolucions, Set<Resolucion> resolucions_1) {
		this.persona = persona;
		this.codigoDocumentoOrigen = codigoDocumentoOrigen;
		this.descripcion = descripcion;
		this.fechaPresentacion = fechaPresentacion;
		this.estadoDocumentoOrigen = estadoDocumentoOrigen;
		this.resolucions = resolucions;
		this.resolucions_1 = resolucions_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_documento_origen", unique = true, nullable = false)
	public Integer getIdDocumentoOrigen() {
		return this.idDocumentoOrigen;
	}

	public void setIdDocumentoOrigen(Integer idDocumentoOrigen) {
		this.idDocumentoOrigen = idDocumentoOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "codigo_documento_origen", nullable = false, length = 60)
	public String getCodigoDocumentoOrigen() {
		return this.codigoDocumentoOrigen;
	}

	public void setCodigoDocumentoOrigen(String codigoDocumentoOrigen) {
		this.codigoDocumentoOrigen = codigoDocumentoOrigen;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_presentacion", length = 10)
	public Date getFechaPresentacion() {
		return this.fechaPresentacion;
	}

	public void setFechaPresentacion(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	@Column(name = "estado_documento_origen", nullable = false, length = 11)
	public String getEstadoDocumentoOrigen() {
		return this.estadoDocumentoOrigen;
	}

	public void setEstadoDocumentoOrigen(String estadoDocumentoOrigen) {
		this.estadoDocumentoOrigen = estadoDocumentoOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoOrigen")
	public Set<Resolucion> getResolucions() {
		return this.resolucions;
	}

	public void setResolucions(Set<Resolucion> resolucions) {
		this.resolucions = resolucions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoOrigen")
	public Set<Resolucion> getResolucions_1() {
		return this.resolucions_1;
	}

	public void setResolucions_1(Set<Resolucion> resolucions_1) {
		this.resolucions_1 = resolucions_1;
	}

}
