package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentoadjuntodatoadicionalId generated by hbm2java
 */
@Embeddable
public class DocumentoadjuntodatoadicionalId implements java.io.Serializable {

	private int idDatoAdicional;
	private int idDocumentoAdjunto;

	public DocumentoadjuntodatoadicionalId() {
	}

	public DocumentoadjuntodatoadicionalId(int idDatoAdicional, int idDocumentoAdjunto) {
		this.idDatoAdicional = idDatoAdicional;
		this.idDocumentoAdjunto = idDocumentoAdjunto;
	}

	@Column(name = "id_dato_adicional", nullable = false)
	public int getIdDatoAdicional() {
		return this.idDatoAdicional;
	}

	public void setIdDatoAdicional(int idDatoAdicional) {
		this.idDatoAdicional = idDatoAdicional;
	}

	@Column(name = "id_documento_adjunto", nullable = false)
	public int getIdDocumentoAdjunto() {
		return this.idDocumentoAdjunto;
	}

	public void setIdDocumentoAdjunto(int idDocumentoAdjunto) {
		this.idDocumentoAdjunto = idDocumentoAdjunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoadjuntodatoadicionalId))
			return false;
		DocumentoadjuntodatoadicionalId castOther = (DocumentoadjuntodatoadicionalId) other;

		return (this.getIdDatoAdicional() == castOther.getIdDatoAdicional())
				&& (this.getIdDocumentoAdjunto() == castOther.getIdDocumentoAdjunto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDatoAdicional();
		result = 37 * result + this.getIdDocumentoAdjunto();
		return result;
	}

}
