package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento", catalog = "cer_db", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo_seguimiento"), @UniqueConstraint(columnNames = "id_resolucion") })
public class Documento implements java.io.Serializable {

	private Integer idDocumento;
	private Solicitud solicitud;
	private Detalledocumento detalledocumento;
	private Estadodocumento estadodocumento;
	private int idTipoDocumento;
	private int idSolicitante;
	private int idDestinatario;
	private int idResolucion;
	private char codigoSeguimiento;
	private Resolucion resolucion;
	private Tipodocumento tipodocumento;
	private Solicitante solicitante;
	private Destinatario destinatario;

	public Documento() {
	}

	public Documento(Solicitud solicitud, Detalledocumento detalledocumento, Estadodocumento estadodocumento,
			int idTipoDocumento, int idSolicitante, int idDestinatario, int idResolucion, char codigoSeguimiento) {
		this.solicitud = solicitud;
		this.detalledocumento = detalledocumento;
		this.estadodocumento = estadodocumento;
		this.idTipoDocumento = idTipoDocumento;
		this.idSolicitante = idSolicitante;
		this.idDestinatario = idDestinatario;
		this.idResolucion = idResolucion;
		this.codigoSeguimiento = codigoSeguimiento;
	}

	public Documento(Solicitud solicitud, Detalledocumento detalledocumento, Estadodocumento estadodocumento,
			int idTipoDocumento, int idSolicitante, int idDestinatario, int idResolucion, char codigoSeguimiento,
			Resolucion resolucion, Tipodocumento tipodocumento, Solicitante solicitante, Destinatario destinatario) {
		this.solicitud = solicitud;
		this.detalledocumento = detalledocumento;
		this.estadodocumento = estadodocumento;
		this.idTipoDocumento = idTipoDocumento;
		this.idSolicitante = idSolicitante;
		this.idDestinatario = idDestinatario;
		this.idResolucion = idResolucion;
		this.codigoSeguimiento = codigoSeguimiento;
		this.resolucion = resolucion;
		this.tipodocumento = tipodocumento;
		this.solicitante = solicitante;
		this.destinatario = destinatario;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "solicitud"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_documento", unique = true, nullable = false)
	public Integer getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Integer idDocumento) {
		this.idDocumento = idDocumento;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_detalle_documento", nullable = false)
	public Detalledocumento getDetalledocumento() {
		return this.detalledocumento;
	}

	public void setDetalledocumento(Detalledocumento detalledocumento) {
		this.detalledocumento = detalledocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_documento", nullable = false)
	public Estadodocumento getEstadodocumento() {
		return this.estadodocumento;
	}

	public void setEstadodocumento(Estadodocumento estadodocumento) {
		this.estadodocumento = estadodocumento;
	}

	@Column(name = "id_tipo_documento", nullable = false)
	public int getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(int idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@Column(name = "id_solicitante", nullable = false)
	public int getIdSolicitante() {
		return this.idSolicitante;
	}

	public void setIdSolicitante(int idSolicitante) {
		this.idSolicitante = idSolicitante;
	}

	@Column(name = "id_destinatario", nullable = false)
	public int getIdDestinatario() {
		return this.idDestinatario;
	}

	public void setIdDestinatario(int idDestinatario) {
		this.idDestinatario = idDestinatario;
	}

	@Column(name = "id_resolucion", unique = true, nullable = false)
	public int getIdResolucion() {
		return this.idResolucion;
	}

	public void setIdResolucion(int idResolucion) {
		this.idResolucion = idResolucion;
	}

	@Column(name = "codigo_seguimiento", unique = true, nullable = false, length = 1)
	public char getCodigoSeguimiento() {
		return this.codigoSeguimiento;
	}

	public void setCodigoSeguimiento(char codigoSeguimiento) {
		this.codigoSeguimiento = codigoSeguimiento;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documento")
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documento")
	public Tipodocumento getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(Tipodocumento tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documento")
	public Solicitante getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(Solicitante solicitante) {
		this.solicitante = solicitante;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documento")
	public Destinatario getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(Destinatario destinatario) {
		this.destinatario = destinatario;
	}

}
