package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Documentoadjuntodatoadicional generated by hbm2java
 */
@Entity
@Table(name = "documentoadjuntodatoadicional", catalog = "cer_db")
public class Documentoadjuntodatoadicional implements java.io.Serializable {

	private DocumentoadjuntodatoadicionalId id;
	private Documentoadjunto documentoadjunto;
	private Datoadicional datoadicional;

	public Documentoadjuntodatoadicional() {
	}

	public Documentoadjuntodatoadicional(DocumentoadjuntodatoadicionalId id) {
		this.id = id;
	}

	public Documentoadjuntodatoadicional(DocumentoadjuntodatoadicionalId id, Documentoadjunto documentoadjunto,
			Datoadicional datoadicional) {
		this.id = id;
		this.documentoadjunto = documentoadjunto;
		this.datoadicional = datoadicional;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDatoAdicional", column = @Column(name = "id_dato_adicional", nullable = false)),
			@AttributeOverride(name = "idDocumentoAdjunto", column = @Column(name = "id_documento_adjunto", nullable = false)) })
	public DocumentoadjuntodatoadicionalId getId() {
		return this.id;
	}

	public void setId(DocumentoadjuntodatoadicionalId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documentoadjuntodatoadicional")
	public Documentoadjunto getDocumentoadjunto() {
		return this.documentoadjunto;
	}

	public void setDocumentoadjunto(Documentoadjunto documentoadjunto) {
		this.documentoadjunto = documentoadjunto;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documentoadjuntodatoadicional")
	public Datoadicional getDatoadicional() {
		return this.datoadicional;
	}

	public void setDatoadicional(Datoadicional datoadicional) {
		this.datoadicional = datoadicional;
	}

}
