package edu.pe.unsch.entity;
// Generated 24-jul-2019 22:01:25 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EscuelaProfesional generated by hbm2java
 */
@Entity
@Table(name = "escuela_profesional", catalog = "cer_db")
public class EscuelaProfesional implements java.io.Serializable {

	private int idEscuelaProfesional;
	private String nombreEscuelaProfesional;
	private Set<Resolucion> resolucions = new HashSet<Resolucion>(0);

	public EscuelaProfesional() {
	}

	public EscuelaProfesional(int idEscuelaProfesional, String nombreEscuelaProfesional) {
		this.idEscuelaProfesional = idEscuelaProfesional;
		this.nombreEscuelaProfesional = nombreEscuelaProfesional;
	}

	public EscuelaProfesional(int idEscuelaProfesional, String nombreEscuelaProfesional, Set<Resolucion> resolucions) {
		this.idEscuelaProfesional = idEscuelaProfesional;
		this.nombreEscuelaProfesional = nombreEscuelaProfesional;
		this.resolucions = resolucions;
	}

	@Id

	@Column(name = "id_escuela_profesional", unique = true, nullable = false)
	public int getIdEscuelaProfesional() {
		return this.idEscuelaProfesional;
	}

	public void setIdEscuelaProfesional(int idEscuelaProfesional) {
		this.idEscuelaProfesional = idEscuelaProfesional;
	}

	@Column(name = "nombre_escuela_profesional", nullable = false, length = 60)
	public String getNombreEscuelaProfesional() {
		return this.nombreEscuelaProfesional;
	}

	public void setNombreEscuelaProfesional(String nombreEscuelaProfesional) {
		this.nombreEscuelaProfesional = nombreEscuelaProfesional;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escuelaProfesional")
	public Set<Resolucion> getResolucions() {
		return this.resolucions;
	}

	public void setResolucions(Set<Resolucion> resolucions) {
		this.resolucions = resolucions;
	}

}
