package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacultadId generated by hbm2java
 */
@Embeddable
public class FacultadId implements java.io.Serializable {

	private Character codFacultad;
	private String nombreFacultad;

	public FacultadId() {
	}

	public FacultadId(String nombreFacultad) {
		this.nombreFacultad = nombreFacultad;
	}

	public FacultadId(Character codFacultad, String nombreFacultad) {
		this.codFacultad = codFacultad;
		this.nombreFacultad = nombreFacultad;
	}

	@Column(name = "cod_facultad", unique = true, length = 1)
	public Character getCodFacultad() {
		return this.codFacultad;
	}

	public void setCodFacultad(Character codFacultad) {
		this.codFacultad = codFacultad;
	}

	@Column(name = "nombre_facultad", nullable = false, length = 50)
	public String getNombreFacultad() {
		return this.nombreFacultad;
	}

	public void setNombreFacultad(String nombreFacultad) {
		this.nombreFacultad = nombreFacultad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacultadId))
			return false;
		FacultadId castOther = (FacultadId) other;

		return ((this.getCodFacultad() == castOther.getCodFacultad()) || (this.getCodFacultad() != null
				&& castOther.getCodFacultad() != null && this.getCodFacultad().equals(castOther.getCodFacultad())))
				&& ((this.getNombreFacultad() == castOther.getNombreFacultad())
						|| (this.getNombreFacultad() != null && castOther.getNombreFacultad() != null
								&& this.getNombreFacultad().equals(castOther.getNombreFacultad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodFacultad() == null ? 0 : this.getCodFacultad().hashCode());
		result = 37 * result + (getNombreFacultad() == null ? 0 : this.getNombreFacultad().hashCode());
		return result;
	}

}
