package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name = "facultad", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "cod_facultad"))
public class Facultad implements java.io.Serializable {

	private FacultadId id;
	private Resolucion resolucion;

	public Facultad() {
	}

	public Facultad(FacultadId id) {
		this.id = id;
	}

	public Facultad(FacultadId id, Resolucion resolucion) {
		this.id = id;
		this.resolucion = resolucion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codFacultad", column = @Column(name = "cod_facultad", unique = true, length = 1)),
			@AttributeOverride(name = "nombreFacultad", column = @Column(name = "nombre_facultad", nullable = false, length = 50)) })
	public FacultadId getId() {
		return this.id;
	}

	public void setId(FacultadId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_facultad", unique = true, insertable = false, updatable = false)
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

}
