package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Firma generated by hbm2java
 */
@Entity
@Table(name = "firma", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "nombre_firma"))
public class Firma implements java.io.Serializable {

	private Integer idFirma;
	private String nombreFirma;
	private byte[] firmaDigital;
	private String cargo;
	private Set<Resolucion> resolucions = new HashSet<Resolucion>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Usuario> usuarios_1 = new HashSet<Usuario>(0);

	public Firma() {
	}

	public Firma(String nombreFirma, byte[] firmaDigital) {
		this.nombreFirma = nombreFirma;
		this.firmaDigital = firmaDigital;
	}

	public Firma(String nombreFirma, byte[] firmaDigital, String cargo, Set<Resolucion> resolucions,
			Set<Usuario> usuarios, Set<Usuario> usuarios_1) {
		this.nombreFirma = nombreFirma;
		this.firmaDigital = firmaDigital;
		this.cargo = cargo;
		this.resolucions = resolucions;
		this.usuarios = usuarios;
		this.usuarios_1 = usuarios_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_firma", unique = true, nullable = false)
	public Integer getIdFirma() {
		return this.idFirma;
	}

	public void setIdFirma(Integer idFirma) {
		this.idFirma = idFirma;
	}

	@Column(name = "nombre_firma", unique = true, nullable = false, length = 80)
	public String getNombreFirma() {
		return this.nombreFirma;
	}

	public void setNombreFirma(String nombreFirma) {
		this.nombreFirma = nombreFirma;
	}

	@Column(name = "firma_digital", nullable = false)
	public byte[] getFirmaDigital() {
		return this.firmaDigital;
	}

	public void setFirmaDigital(byte[] firmaDigital) {
		this.firmaDigital = firmaDigital;
	}

	@Column(name = "cargo", length = 30)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firma")
	public Set<Resolucion> getResolucions() {
		return this.resolucions;
	}

	public void setResolucions(Set<Resolucion> resolucions) {
		this.resolucions = resolucions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firma")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firma")
	public Set<Usuario> getUsuarios_1() {
		return this.usuarios_1;
	}

	public void setUsuarios_1(Set<Usuario> usuarios_1) {
		this.usuarios_1 = usuarios_1;
	}

}
