package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fundamento generated by hbm2java
 */
@Entity
@Table(name = "fundamento", catalog = "cer_db")
public class Fundamento implements java.io.Serializable {

	private Integer idConsideracionResolucion;
	private Resolucion resolucion;
	private String considerando;

	public Fundamento() {
	}

	public Fundamento(Resolucion resolucion, String considerando) {
		this.resolucion = resolucion;
		this.considerando = considerando;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_consideracion_resolucion", unique = true, nullable = false)
	public Integer getIdConsideracionResolucion() {
		return this.idConsideracionResolucion;
	}

	public void setIdConsideracionResolucion(Integer idConsideracionResolucion) {
		this.idConsideracionResolucion = idConsideracionResolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion", nullable = false)
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "considerando", nullable = false)
	public String getConsiderando() {
		return this.considerando;
	}

	public void setConsiderando(String considerando) {
		this.considerando = considerando;
	}

}
