package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Memorando generated by hbm2java
 */
@Entity
@Table(name = "memorando", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "id_documento"))
public class Memorando implements java.io.Serializable {

	private Integer idMemorando;
	private Integer idDocumento;
	private String asuntoMemorando;
	private Documento documento;

	public Memorando() {
	}

	public Memorando(String asuntoMemorando) {
		this.asuntoMemorando = asuntoMemorando;
	}

	public Memorando(Integer idDocumento, String asuntoMemorando, Documento documento) {
		this.idDocumento = idDocumento;
		this.asuntoMemorando = asuntoMemorando;
		this.documento = documento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_memorando", unique = true, nullable = false)
	public Integer getIdMemorando() {
		return this.idMemorando;
	}

	public void setIdMemorando(Integer idMemorando) {
		this.idMemorando = idMemorando;
	}

	@Column(name = "id_documento", unique = true)
	public Integer getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Integer idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "asunto_memorando", nullable = false)
	public String getAsuntoMemorando() {
		return this.asuntoMemorando;
	}

	public void setAsuntoMemorando(String asuntoMemorando) {
		this.asuntoMemorando = asuntoMemorando;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

}
