package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Oficio generated by hbm2java
 */
@Entity
@Table(name = "oficio", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "id_documento"))
public class Oficio implements java.io.Serializable {

	private Integer idOficio;
	private Integer idDocumento;
	private String membrete;
	private String asunto;
	private String despedida;
	private Documento documento;

	public Oficio() {
	}

	public Oficio(String membrete, String asunto, String despedida) {
		this.membrete = membrete;
		this.asunto = asunto;
		this.despedida = despedida;
	}

	public Oficio(Integer idDocumento, String membrete, String asunto, String despedida, Documento documento) {
		this.idDocumento = idDocumento;
		this.membrete = membrete;
		this.asunto = asunto;
		this.despedida = despedida;
		this.documento = documento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_oficio", unique = true, nullable = false)
	public Integer getIdOficio() {
		return this.idOficio;
	}

	public void setIdOficio(Integer idOficio) {
		this.idOficio = idOficio;
	}

	@Column(name = "id_documento", unique = true)
	public Integer getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Integer idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "membrete", nullable = false)
	public String getMembrete() {
		return this.membrete;
	}

	public void setMembrete(String membrete) {
		this.membrete = membrete;
	}

	@Column(name = "asunto", nullable = false)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "despedida", nullable = false)
	public String getDespedida() {
		return this.despedida;
	}

	public void setDespedida(String despedida) {
		this.despedida = despedida;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

}
