package edu.pe.unsch.entity;
// Generated 24-jul-2019 22:01:25 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", catalog = "cer_db", uniqueConstraints = { @UniqueConstraint(columnNames = "codigo"),
		@UniqueConstraint(columnNames = "dni") })
public class Persona implements java.io.Serializable {

	private int idPersona;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String cargo;
	private String dni;
	private String direccion;
	private String codigo;
	private Set<DocumentoOrigen> documentoOrigens = new HashSet<DocumentoOrigen>(0);

	public Persona() {
	}

	public Persona(int idPersona, String nombres, String apellidoPaterno, String apellidoMaterno, String dni,
			String direccion, String codigo) {
		this.idPersona = idPersona;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.dni = dni;
		this.direccion = direccion;
		this.codigo = codigo;
	}

	public Persona(int idPersona, String nombres, String apellidoPaterno, String apellidoMaterno, String cargo,
			String dni, String direccion, String codigo, Set<DocumentoOrigen> documentoOrigens) {
		this.idPersona = idPersona;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.cargo = cargo;
		this.dni = dni;
		this.direccion = direccion;
		this.codigo = codigo;
		this.documentoOrigens = documentoOrigens;
	}

	@Id

	@Column(name = "id_persona", unique = true, nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellido_paterno", nullable = false, length = 30)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellido_materno", nullable = false, length = 30)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "cargo", length = 30)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "dni", unique = true, nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<DocumentoOrigen> getDocumentoOrigens() {
		return this.documentoOrigens;
	}

	public void setDocumentoOrigens(Set<DocumentoOrigen> documentoOrigens) {
		this.documentoOrigens = documentoOrigens;
	}

}
