package edu.pe.unsch.entity;
// Generated 21-jul-2019 23:43:06 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Resolucion generated by hbm2java
 */
@Entity
@Table(name = "resolucion", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_resolucion"))
public class Resolucion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idResolucion;
	private DocumentoOrigen documentoOrigen;
	private EscuelaProfesional escuelaProfesional;
	private Facultad facultad;
	private Firma firma;
	private String tipoResolucion;
	private String codigoResolucion;
	private String lugar;
	private Date fechaEmision;
	private Set<Fundamento> fundamentos = new HashSet<Fundamento>(0);
	private Set<Cc> ccs = new HashSet<Cc>(0);
	private Set<Dictamen> dictamens = new HashSet<Dictamen>(0);

	public Resolucion() {
	}

	public Resolucion(DocumentoOrigen documentoOrigen, Facultad facultad, String tipoResolucion,
			String codigoResolucion) {
		this.documentoOrigen = documentoOrigen;
		this.facultad = facultad;
		this.tipoResolucion = tipoResolucion;
		this.codigoResolucion = codigoResolucion;
	}

	public Resolucion(DocumentoOrigen documentoOrigen, EscuelaProfesional escuelaProfesional, Facultad facultad,
			Firma firma, String tipoResolucion, String codigoResolucion, String lugar, Date fechaEmision,
			Set<Fundamento> fundamentos, Set<Cc> ccs, Set<Dictamen> dictamens) {
		this.documentoOrigen = documentoOrigen;
		this.escuelaProfesional = escuelaProfesional;
		this.facultad = facultad;
		this.firma = firma;
		this.tipoResolucion = tipoResolucion;
		this.codigoResolucion = codigoResolucion;
		this.lugar = lugar;
		this.fechaEmision = fechaEmision;
		this.fundamentos = fundamentos;
		this.ccs = ccs;
		this.dictamens = dictamens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_resolucion", unique = true, nullable = false)
	public Integer getIdResolucion() {
		return this.idResolucion;
	}

	public void setIdResolucion(Integer idResolucion) {
		this.idResolucion = idResolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_origen", nullable = false)
	public DocumentoOrigen getDocumentoOrigen() {
		return this.documentoOrigen;
	}

	public void setDocumentoOrigen(DocumentoOrigen documentoOrigen) {
		this.documentoOrigen = documentoOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_escuela_profesional")
	public EscuelaProfesional getEscuelaProfesional() {
		return this.escuelaProfesional;
	}

	public void setEscuelaProfesional(EscuelaProfesional escuelaProfesional) {
		this.escuelaProfesional = escuelaProfesional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_facultad", nullable = false)
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_firma")
	public Firma getFirma() {
		return this.firma;
	}

	public void setFirma(Firma firma) {
		this.firma = firma;
	}

	@Column(name = "tipo_resolucion", nullable = false, length = 33)
	public String getTipoResolucion() {
		return this.tipoResolucion;
	}

	public void setTipoResolucion(String tipoResolucion) {
		this.tipoResolucion = tipoResolucion;
	}

	@Column(name = "codigo_resolucion", unique = true, nullable = false, length = 60)
	public String getCodigoResolucion() {
		return this.codigoResolucion;
	}

	public void setCodigoResolucion(String codigoResolucion) {
		this.codigoResolucion = codigoResolucion;
	}

	@Column(name = "lugar", length = 30)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_emision", length = 10)
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Fundamento> getFundamentos() {
		return this.fundamentos;
	}

	public void setFundamentos(Set<Fundamento> fundamentos) {
		this.fundamentos = fundamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Cc> getCcs() {
		return this.ccs;
	}

	public void setCcs(Set<Cc> ccs) {
		this.ccs = ccs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Dictamen> getDictamens() {
		return this.dictamens;
	}

	public void setDictamens(Set<Dictamen> dictamens) {
		this.dictamens = dictamens;
	}

}
