package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Resolucion generated by hbm2java
 */
@Entity
@Table(name = "resolucion", catalog = "cer_db", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_resolucion"))
public class Resolucion implements java.io.Serializable {

	private Integer idResolucion;
	private Documento documento;
	private int idTipoResolucion;
	private String codigoResolucion;
	private char codFacultad;
	private Tiporesolucion tiporesolucion;
	private Set<Consideracionresolucion> consideracionresolucions = new HashSet<Consideracionresolucion>(0);
	private Set<Facultad> facultads = new HashSet<Facultad>(0);

	public Resolucion() {
	}

	public Resolucion(Documento documento, int idTipoResolucion, char codFacultad) {
		this.documento = documento;
		this.idTipoResolucion = idTipoResolucion;
		this.codFacultad = codFacultad;
	}

	public Resolucion(Documento documento, int idTipoResolucion, String codigoResolucion, char codFacultad,
			Tiporesolucion tiporesolucion, Set<Consideracionresolucion> consideracionresolucions,
			Set<Facultad> facultads) {
		this.documento = documento;
		this.idTipoResolucion = idTipoResolucion;
		this.codigoResolucion = codigoResolucion;
		this.codFacultad = codFacultad;
		this.tiporesolucion = tiporesolucion;
		this.consideracionresolucions = consideracionresolucions;
		this.facultads = facultads;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "documento"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_resolucion", unique = true, nullable = false)
	public Integer getIdResolucion() {
		return this.idResolucion;
	}

	public void setIdResolucion(Integer idResolucion) {
		this.idResolucion = idResolucion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "id_tipo_resolucion", nullable = false)
	public int getIdTipoResolucion() {
		return this.idTipoResolucion;
	}

	public void setIdTipoResolucion(int idTipoResolucion) {
		this.idTipoResolucion = idTipoResolucion;
	}

	@Column(name = "codigo_resolucion", unique = true, length = 60)
	public String getCodigoResolucion() {
		return this.codigoResolucion;
	}

	public void setCodigoResolucion(String codigoResolucion) {
		this.codigoResolucion = codigoResolucion;
	}

	@Column(name = "cod_facultad", nullable = false, length = 1)
	public char getCodFacultad() {
		return this.codFacultad;
	}

	public void setCodFacultad(char codFacultad) {
		this.codFacultad = codFacultad;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Tiporesolucion getTiporesolucion() {
		return this.tiporesolucion;
	}

	public void setTiporesolucion(Tiporesolucion tiporesolucion) {
		this.tiporesolucion = tiporesolucion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Consideracionresolucion> getConsideracionresolucions() {
		return this.consideracionresolucions;
	}

	public void setConsideracionresolucions(Set<Consideracionresolucion> consideracionresolucions) {
		this.consideracionresolucions = consideracionresolucions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Facultad> getFacultads() {
		return this.facultads;
	}

	public void setFacultads(Set<Facultad> facultads) {
		this.facultads = facultads;
	}

}
