package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Solicitante generated by hbm2java
 */
@Entity
@Table(name = "solicitante", catalog = "cer_db", uniqueConstraints = { @UniqueConstraint(columnNames = "codigo"),
		@UniqueConstraint(columnNames = "dni") })
public class Solicitante implements java.io.Serializable {

	private Integer idSolicitante;
	private Documento documento;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private char codigo;
	private char dni;
	private String direccion;

	public Solicitante() {
	}

	public Solicitante(Documento documento, String nombres, String apellidoPaterno, String apellidoMaterno, char codigo,
			char dni) {
		this.documento = documento;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.codigo = codigo;
		this.dni = dni;
	}

	public Solicitante(Documento documento, String nombres, String apellidoPaterno, String apellidoMaterno, char codigo,
			char dni, String direccion) {
		this.documento = documento;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.codigo = codigo;
		this.dni = dni;
		this.direccion = direccion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "documento"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_solicitante", unique = true, nullable = false)
	public Integer getIdSolicitante() {
		return this.idSolicitante;
	}

	public void setIdSolicitante(Integer idSolicitante) {
		this.idSolicitante = idSolicitante;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellido_paterno", nullable = false, length = 50)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellido_materno", nullable = false, length = 50)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 1)
	public char getCodigo() {
		return this.codigo;
	}

	public void setCodigo(char codigo) {
		this.codigo = codigo;
	}

	@Column(name = "dni", unique = true, nullable = false, length = 1)
	public char getDni() {
		return this.dni;
	}

	public void setDni(char dni) {
		this.dni = dni;
	}

	@Column(name = "direccion", length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
