package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tiporesolucion generated by hbm2java
 */
@Entity
@Table(name = "tiporesolucion", catalog = "cer_db")
public class Tiporesolucion implements java.io.Serializable {

	private Integer idTipoResolucion;
	private Resolucion resolucion;
	private String tipoResolucion;

	public Tiporesolucion() {
	}

	public Tiporesolucion(Resolucion resolucion, String tipoResolucion) {
		this.resolucion = resolucion;
		this.tipoResolucion = tipoResolucion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "resolucion"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_tipo_resolucion", unique = true, nullable = false)
	public Integer getIdTipoResolucion() {
		return this.idTipoResolucion;
	}

	public void setIdTipoResolucion(Integer idTipoResolucion) {
		this.idTipoResolucion = idTipoResolucion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "tipo_resolucion", nullable = false, length = 50)
	public String getTipoResolucion() {
		return this.tipoResolucion;
	}

	public void setTipoResolucion(String tipoResolucion) {
		this.tipoResolucion = tipoResolucion;
	}

}
