package edu.pe.unsch.entity;
// Generated 04-jul-2019 20:41:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tipodocumento generated by hbm2java
 */
@Entity
@Table(name = "tipodocumento", catalog = "cer_db")
public class Tipodocumento implements java.io.Serializable {

	private Integer idTipoDocumento;
	private Documento documento;
	private String tipoDocumento;

	public Tipodocumento() {
	}

	public Tipodocumento(Documento documento, String tipoDocumento) {
		this.documento = documento;
		this.tipoDocumento = tipoDocumento;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "documento"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_tipo_documento", unique = true, nullable = false)
	public Integer getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(Integer idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "tipo_documento", nullable = false, length = 50)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

}
